# Generated by Django 5.1.6 on 2025-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_vendedor_direccion_alter_ventadetalle_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
