# Generated by Django 5.1.6 on 2025-02-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_vendedor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='gps_latitud',
            field=models.FloatField(default=-34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='gps_longitud',
            field=models.FloatField(default='-34'),
            preserve_default=False,
        ),
    ]
